name: daily-devcard
on:
  workflow_dispatch:
  push:
    branches:
      - master
  schedule:
    - cron: "0 0 * * *"
jobs:
  devcard:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: devcard
        uses: dailydotdev/action-devcard@3.2.1
        with:
          user_id: ${{ secrets.DAILYDEV_USER }}
          commit_message: "chore: update ${filename}"
