name: Update badges

on:
  workflow_dispatch: # run manually
jobs:
  update-badges:
    name: Update Readme with badges
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Badges - Readme
        uses: pemtajo/badge-readme@3.1.0
        with:
          CREDLY_SORT: RECENT
          CREDLY_USER: xuanken-tay
